name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print Password
        env: 
          MY_PASSWORD: ${{ secrets.PASSWORD }}
        run: echo My password is $MY_PASSWORD
